version: "3.7"

services:
  mysql:
    container_name: mysql_house
    image: mysql:5.7
    ports:
      - "33306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root-pass
      - MYSQL_USER=house
      - MYSQL_PASSWORD=house
      - MYSQL_DATABASE=house
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    volumes:
      - ./mysql:/var/lib/mysql